"""Update 19

Revision ID: 863f9124e50e
Revises: 
Create Date: 2023-05-14 10:54:03.428933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863f9124e50e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usr', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'usr', ['recipient_id'], ['id'])

    with op.batch_alter_table('total_project_average', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('total_project_average', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
